language: python
python:
    - 2.7
    - 3.3
before_install:
    - sudo apt-get install libopenmpi-dev
    - sudo apt-get install openmpi-bin
    - pip install numpy
    - pip install pyzmq --install-option="--zmq=bundled"
    - pip install ipython
    - pip install mpi4py --allow-all-external --allow-unverified mpi4py
    - pip install six
    - pip freeze
install:
    - python setup.py install
before_script:
    - (cd $TRAVIS_BUILD_DIR && make setup_cluster)
script:
    - (cd $TRAVIS_BUILD_DIR && make test)
after_script:
    - (cd $TRAVIS_BUILD_DIR && make teardown_cluster)
